name: quran_publisher_desktop
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.5+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  bidi: ^2.0.12
  collection: ^1.18.0
  drift_flutter: ^0.2.1
  drift: ^2.21.0
  flutter_bidi_text: ^1.0.2
  gap: ^3.0.1
  google_fonts: ^8.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.26
  sqlite3: ^2.4.7
  toastification: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  drift_dev: ^2.21.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # If the editor complains about missing fonts, remember to initialize the
  # submodules. See README for details.
  assets:
    - fonts/quran-fonts/fonts/King Fahd Complex/Original/
    - fonts/quran-fonts/fonts/King Fahd Complex/Original/Hafs-QCF4/
    - fonts/quran-fonts/fonts/King Fahd Complex/Hafs-QCF4-Colors/
    - assets/database/
    - assets/logo/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: QCF4_Surah_Juzuk_Mudah
      fonts:
        - asset: fonts/quran-fonts/fonts/King Fahd Complex/Custom/QCF4_Surah_Juzuk_Mudah-Regular.ttf
