name: Linux ARM64 (Portable)

on:
  workflow_dispatch:

jobs:
  build_linux_arm64:
    name: ğŸ§ Build Linux ARM64 App
    # partner images: https://github.com/actions/partner-runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Flutter arm only available on master for now https://github.com/subosito/flutter-action/issues/345#issuecomment-2657332687
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.35.6

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux --release

      - name: Upload App to artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: build/linux/arm64/release/bundle/
